// JavaScript File

objetivos = ['Atacar, Matar, Destruir',
             'Encontrar, Recuperar',
             'Roubar, Capturar',
             'Vigiar, Proteger',
             'Explorar, Descobrir',
             'Sobreviver, Escapar'];
             
objetivosEsp = [
    ['Pessoa Influente',
     'Organização',
     'Comunidade',
     'Artefato',
     'Monstro',
     'Locação'],
    ['Pessoa Importante',
    'Pessoa Desaparecida',
    'Locação',
    'Objeto Perdido ou Roubado',
    'Espécime Raro',
    'Ingrediente Mágico'],
    ['Obra de Arte ou Joia',
    'Artefato Mágico',
    'Pessoa Importante',
    'Criatura Poderosa',
    'Grimório',
    'Mapa ou Pergaminho Importante'],
    ['Comunidade',
    'Locação',
    'Pessoa Importante',
    'Artefato Mágico',
    'Segredo',
    'Organização'],
    ['Novo Caminho',
    'Ilha Perdida',
    'Ruínas',
    'Novo Ritual',
    'As Catacumbas da Cidade-Estado',
    'A Verdade sobre uma Lenda'],
    ['Naufrágio',
    'Prisão',
    'Assassinos',
    'Culto Caótico',
    'Desastre Natural',
    'Bruxo Vingativo']
    ];

locacoes = ['Ruínas',
            'Lugar Isolado',
            'Cidade-Estado',
            'Região Fronteiriça',
            'Região Selvagem',
            'Lugares Estranhos'];
            
locacoesEsp = [
    ['Antiga Cidade-Estado',
     'Torre do Feiticeiro',
     'Forte',
     'Tumba do Rei-Bruxo',
     'Pequeno Vilarejo',
     'Templo de um Deus Esquecido'],
    ['Ilha Perdida Exótica',
    'Terra dos Mortos',
    'Vale Proibido',
    'Norte Distante',
    'Topo de uma Montanha',
    'Caverna no Centro da Terra'],
    ['Templo Local',
    'Palácio Nobre',
    'Armazém da Guilda Mercantil',
    'Museu',
    'Pocilga',
    'Esgotos'],
    ['Forte Local',
    'Pequeno Vilarejo',
    'Complexo de Cavernas Próximo',
    'Floresta Sombria',
    'Território Inimigo',
    'A Última Estalagem Amiga'],
    ['Selva Cheia de Canibais',
    'Deserto dos Salteadores',
    'Pântano Maldito',
    'Caverna dos Mortos',
    'Montanhas Além do Horizonte',
    'Floresta Demoníaca'],
    ['Ruínas Sobre um Vulcão',
    'Cavernas de Cristal',
    'Cabana da Bruxa',
    'Pirâmide Voadora',
    'Espaçonave Perdida',
    'Torre Invisível']
    ];
    
antagonistas = ['Pessoa Poderosa',
            'Artefato Mágico',
            'Organização',
            'Monstro Irracional',
            'Monstro Inteligente',
            'Entidade Sobrenatural'];

antagonistasEsp = [
    ['Necromante Temido',
     'Líder Bárbaro',
     'Sacerdote do Caos',
     'Nobre Insano',
     'Pirata Sanguinário',
     'Lorde do Crime'],
    ['Golem Descontrolado',
    'Joia com Alma de um Feiticeiro',
    'Espada Demoníaca',
    'Orbe Alienígena',
    'Relíquia dos Deuses Antigos',
    'Estatueta que Controla Mentes'],
    ['Guilda Mercantil Corrupta',
    'Culto Caótico',
    'Companhia de Mercenários Cruéis',
    'Clã de Assassinos',
    'Sociedade Secreta',
    'Grupo de Aventureiros'],
    ['Primordial Desperto',
    'Fera das Sombras',
    'Experimento Arcano que Deu Errado',
    'Animal Pré-Histórico Gigante',
    'Horda de Insetos Gigantes',
    'Humanoides Vampíricos Primitivos'],
    ['Morto-Vivo Poderoso',
    'Demônio',
    'Alienígena',
    'Homem-Serpente',
    'Metamorfo',
    'Homem Ancestral'],
    ['Deus Antigo Esquecido',
    'Fantasma Vingativo',
    'Ser de Outra Dimensão',
    'Espírito Antigo',
    'Imortal',
    'Energia Viva']
    ];
    
coadjuvantes = ['Aventureiro',
            'Pessoa Poderosa',
            'Organização',
            'Monstro',
            'Entidade Sobrenatural',
            'Artefato Mágico'];

coadjuvantesEsp = [
    ['Skald Andarilho',
     'Ladrão Bon-Vivant',
     'Bárbaro Honrado',
     'Peregrino',
     'Feiticeiro Excêntrico',
     'Cavaleiro Errante'],
    ['Capitão de um Navio',
     'Nobre Local',
     'Líder de Guilda Influente',
     'Xamã Ancião',
     'Sábio',
     'Líder Militar'],
    ['Companhia de Mercenários',
     'Ordem Religiosa',
     'Guilda Influente',
     'Sociedade Secreta',
     'Comunidade Local',
     'Grupo de Aventureiros'],
    ['Mutante Deformado',
     'Alienígena',
     'Homem Ancestral',
     'Criatura Mitológica',
     'Animal Inteligente',
     'Morto-Vivo'],
    ['Deus Esquecido',
     'Ser de Outra Dimensão',
     'Espírito Antigo',
     'Imortal',
     'Fantasma',
     'Emoção Viva'],
    ['Espada com Alma',
     'Amuleto Sagrado',
     'Tecnologia Alienígena',
     'Cristal Vivo',
     'Armadura Viva',
     'Estátua Animada']
    ];

complicacoes = ['Recursos',
                'Vítimas',
                'Perigos',
                'Facções',
                'Sobrenatural',
                'Revelações'
               ];
               
complicacoesEsp = [
    ['Grande Tesouro em Risco',
    'Escassez de Comida e Água',
    'Inimigos com Recursos Inesgotáveis',
    'As Armas dos Personagens são Inúteis',
    'Algo Deixa as Magias Mais Perigosas',
    'O Grupo é Roubado'],
    ['Muitos Inocentes Afetados',
    'Pessoa Querida em Perigo',
    'Rival Pedindo Ajuda',
    'Nobre Arrogante',
    'Monstro Inocente',
    'Entidade Sobrenatural'],
    ['Tempestade Furiosa',
    'Monstro Enfurecido',
    'Vulcão Ativo',
    'Catástrofe Mágica',
    'Plantas Perigosas',
    'Bestas Selvagens'],
    ['Grupo de Aventureiros Rival',
    'Culto Querendo Manter Status Quo',
    'Mercenarios Gananciosos',
    'Culto Apocalíptico',
    'Casa Nobre Traidora',
    'Inimigo do Antagonista Querendo Seu Lugar'],
    ['Maldição',
    'Locação Fica em Outro Plano',
    'Fantasmas das Vítimas Confusos',
    'Local Tabu para Cultura Local',
    'Proteção Mágica',
    'Alienígena Perdido'],
    ['Vítimas não São o que Parecem',
    'Antagonista não é o que Parece',
    'Traição é Descoberta',
    'Inimigo Oculto se Revela',
    'Inimigo se Revela Aliado',
    'O que Parece Sobrenatural não é']
    ];
    
recompensas = ['Tesouros',
               'Artefatos Mágicos',
               'Poder',
               'Conhecimento',
               'Influência',
               'Glória'];

recompensasEsp = [
    ['Grande Quantidade de Ouro e Prata',
    'Pedra Preciosa Gigantesca',
    'Ídolo Sagrado Inestimável',
    'Joia Lendária',
    'Obra de Arte Preciosa',
    'Ingredientes Mágicos'],
    ['Espada Lendária',
    'Grimório Antigo',
    'Artefato Alienígena',
    'Máquina Tecnológica',
    'Instrumento Musical',
    'Cristal de Energia'],
    ['Magia Poderosa',
    'Poder Sobre uma Criatura',
    'Imortalidade',
    'Força Sobrenatural',
    'Poder Sobre um Grupo',
    'Favor de um Ser Poderoso'],
    ['Verdade Sobre uma Lenda',
    'Localização de um Tesouro Lendário',
    'Nome Verdadeiro de uma Entidade',
    'Segredo de Estado',
    'Fraqueza de um Inimigo',
    'Verdade Sobre o Passado'],
    ['Em uma Cidade-Estado',
    'Em uma Guilda Influente',
    'Sobre uma Sociedade Secreta',
    'Sobre uma Casa Nobre',
    'Com uma Entidade Sobrenatural',
    'Com uma Tribo Selvagem'],
    ['Fama entre Ladrões',
    'Coragem Reconhecida',
    'Grande Celebração pela Comunidade',
    'Título de Nobreza',
    'Entre Seu Próprio Povo',
    'Entre os Seres de Outra Dimensão']
    ];
    